// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/test;

configurable http:CredentialsConfig & readonly authConfig = ?;
ConnectionConfig config = {auth : authConfig};
Client baseClient = check new Client(config, serviceUrl = "https://api.twilio.com");

@test:Config {}
isolated function  testListAccount() {
}

@test:Config {}
isolated function  testCreateAccount() {
}

@test:Config {}
isolated function  testFetchAccount() {
}

@test:Config {}
isolated function  testUpdateAccount() {
}

@test:Config {}
isolated function  testListAddress() {
}

@test:Config {}
isolated function  testCreateAddress() {
}

@test:Config {}
isolated function  testFetchAddress() {
}

@test:Config {}
isolated function  testUpdateAddress() {
}

@test:Config {}
isolated function  testDeleteAddress() {
}

@test:Config {}
isolated function  testListApplication() {
}

@test:Config {}
isolated function  testCreateApplication() {
}

@test:Config {}
isolated function  testFetchApplication() {
}

@test:Config {}
isolated function  testUpdateApplication() {
}

@test:Config {}
isolated function  testDeleteApplication() {
}

@test:Config {}
isolated function  testFetchAuthorizedConnectApp() {
}

@test:Config {}
isolated function  testListAuthorizedConnectApp() {
}

@test:Config {}
isolated function  testListAvailablePhoneNumberCountry() {
}

@test:Config {}
isolated function  testFetchAvailablePhoneNumberCountry() {
}

@test:Config {}
isolated function  testListAvailablePhoneNumberLocal() {
}

@test:Config {}
isolated function  testListAvailablePhoneNumberMachineToMachine() {
}

@test:Config {}
isolated function  testListAvailablePhoneNumberMobile() {
}

@test:Config {}
isolated function  testListAvailablePhoneNumberNational() {
}

@test:Config {}
isolated function  testListAvailablePhoneNumberSharedCost() {
}

@test:Config {}
isolated function  testListAvailablePhoneNumberTollFree() {
}

@test:Config {}
isolated function  testListAvailablePhoneNumberVoip() {
}

@test:Config {}
isolated function  testFetchBalance() {
}

@test:Config {}
isolated function  testListCall() {
}

@test:Config {}
isolated function  testCreateCall() {
}

@test:Config {}
isolated function  testFetchCall() {
}

@test:Config {}
isolated function  testUpdateCall() {
}

@test:Config {}
isolated function  testDeleteCall() {
}

@test:Config {}
isolated function  testListCallEvent() {
}

@test:Config {}
isolated function  testFetchCallFeedback() {
}

@test:Config {}
isolated function  testUpdateCallFeedback() {
}

@test:Config {}
isolated function  testCreateCallFeedbackSummary() {
}

@test:Config {}
isolated function  testFetchCallFeedbackSummary() {
}

@test:Config {}
isolated function  testDeleteCallFeedbackSummary() {
}

@test:Config {}
isolated function  testFetchCallNotification() {
}

@test:Config {}
isolated function  testListCallNotification() {
}

@test:Config {}
isolated function  testListCallRecording() {
}

@test:Config {}
isolated function  testCreateCallRecording() {
}

@test:Config {}
isolated function  testFetchCallRecording() {
}

@test:Config {}
isolated function  testUpdateCallRecording() {
}

@test:Config {}
isolated function  testDeleteCallRecording() {
}

@test:Config {}
isolated function  testFetchConference() {
}

@test:Config {}
isolated function  testUpdateConference() {
}

@test:Config {}
isolated function  testListConference() {
}

@test:Config {}
isolated function  testFetchConferenceRecording() {
}

@test:Config {}
isolated function  testUpdateConferenceRecording() {
}

@test:Config {}
isolated function  testDeleteConferenceRecording() {
}

@test:Config {}
isolated function  testListConferenceRecording() {
}

@test:Config {}
isolated function  testFetchConnectApp() {
}

@test:Config {}
isolated function  testUpdateConnectApp() {
}

@test:Config {}
isolated function  testDeleteConnectApp() {
}

@test:Config {}
isolated function  testListConnectApp() {
}

@test:Config {}
isolated function  testListDependentPhoneNumber() {
}

@test:Config {}
isolated function  testFetchIncomingPhoneNumber() {
}

@test:Config {}
isolated function  testUpdateIncomingPhoneNumber() {
}

@test:Config {}
isolated function  testDeleteIncomingPhoneNumber() {
}

@test:Config {}
isolated function  testListIncomingPhoneNumber() {
}

@test:Config {}
isolated function  testCreateIncomingPhoneNumber() {
}

@test:Config {}
isolated function  testFetchIncomingPhoneNumberAssignedAddOn() {
}

@test:Config {}
isolated function  testDeleteIncomingPhoneNumberAssignedAddOn() {
}

@test:Config {}
isolated function  testListIncomingPhoneNumberAssignedAddOn() {
}

@test:Config {}
isolated function  testCreateIncomingPhoneNumberAssignedAddOn() {
}

@test:Config {}
isolated function  testFetchIncomingPhoneNumberAssignedAddOnExtension() {
}

@test:Config {}
isolated function  testListIncomingPhoneNumberAssignedAddOnExtension() {
}

@test:Config {}
isolated function  testListIncomingPhoneNumberLocal() {
}

@test:Config {}
isolated function  testCreateIncomingPhoneNumberLocal() {
}

@test:Config {}
isolated function  testListIncomingPhoneNumberMobile() {
}

@test:Config {}
isolated function  testCreateIncomingPhoneNumberMobile() {
}

@test:Config {}
isolated function  testListIncomingPhoneNumberTollFree() {
}

@test:Config {}
isolated function  testCreateIncomingPhoneNumberTollFree() {
}

@test:Config {}
isolated function  testFetchKey() {
}

@test:Config {}
isolated function  testUpdateKey() {
}

@test:Config {}
isolated function  testDeleteKey() {
}

@test:Config {}
isolated function  testListKey() {
}

@test:Config {}
isolated function  testCreateNewKey() {
}

@test:Config {}
isolated function  testFetchMedia() {
}

@test:Config {}
isolated function  testDeleteMedia() {
}

@test:Config {}
isolated function  testListMedia() {
}

@test:Config {}
isolated function  testFetchMember() {
}

@test:Config {}
isolated function  testUpdateMember() {
}

@test:Config {}
isolated function  testListMember() {
}

@test:Config {}
isolated function  testListMessage() {
}

@test:Config {}
isolated function  testCreateMessage() {
}

@test:Config {}
isolated function  testFetchMessage() {
}

@test:Config {}
isolated function  testUpdateMessage() {
}

@test:Config {}
isolated function  testDeleteMessage() {
}

@test:Config {}
isolated function  testCreateMessageFeedback() {
}

@test:Config {}
isolated function  testListSigningKey() {
}

@test:Config {}
isolated function  testCreateNewSigningKey() {
}

@test:Config {}
isolated function  testFetchNotification() {
}

@test:Config {}
isolated function  testListNotification() {
}

@test:Config {}
isolated function  testFetchOutgoingCallerId() {
}

@test:Config {}
isolated function  testUpdateOutgoingCallerId() {
}

@test:Config {}
isolated function  testDeleteOutgoingCallerId() {
}

@test:Config {}
isolated function  testListOutgoingCallerId() {
}

@test:Config {}
isolated function  testCreateValidationRequest() {
}

@test:Config {}
isolated function  testFetchParticipant() {
}

@test:Config {}
isolated function  testUpdateParticipant() {
}

@test:Config {}
isolated function  testDeleteParticipant() {
}

@test:Config {}
isolated function  testListParticipant() {
}

@test:Config {}
isolated function  testCreateParticipant() {
}

@test:Config {}
isolated function  testCreatePayments() {
}

@test:Config {}
isolated function  testUpdatePayments() {
}

@test:Config {}
isolated function  testFetchQueue() {
}

@test:Config {}
isolated function  testUpdateQueue() {
}

@test:Config {}
isolated function  testDeleteQueue() {
}

@test:Config {}
isolated function  testListQueue() {
}

@test:Config {}
isolated function  testCreateQueue() {
}

@test:Config {}
isolated function  testFetchRecording() {
}

@test:Config {}
isolated function  testDeleteRecording() {
}

@test:Config {}
isolated function  testListRecording() {
}

@test:Config {}
isolated function  testFetchRecordingAddOnResult() {
}

@test:Config {}
isolated function  testDeleteRecordingAddOnResult() {
}

@test:Config {}
isolated function  testListRecordingAddOnResult() {
}

@test:Config {}
isolated function  testFetchRecordingAddOnResultPayload() {
}

@test:Config {}
isolated function  testDeleteRecordingAddOnResultPayload() {
}

@test:Config {}
isolated function  testListRecordingAddOnResultPayload() {
}

@test:Config {}
isolated function  testFetchRecordingTranscription() {
}

@test:Config {}
isolated function  testDeleteRecordingTranscription() {
}

@test:Config {}
isolated function  testListRecordingTranscription() {
}

@test:Config {}
isolated function  testFetchSafelist() {
}

@test:Config {}
isolated function  testCreateSafelist() {
}

@test:Config {}
isolated function  testDeleteSafelist() {
}

@test:Config {}
isolated function  testFetchShortCode() {
}

@test:Config {}
isolated function  testUpdateShortCode() {
}

@test:Config {}
isolated function  testListShortCode() {
}

@test:Config {}
isolated function  testFetchSigningKey() {
}

@test:Config {}
isolated function  testUpdateSigningKey() {
}

@test:Config {}
isolated function  testDeleteSigningKey() {
}

@test:Config {}
isolated function  testListSipAuthCallsCredentialListMapping() {
}

@test:Config {}
isolated function  testCreateSipAuthCallsCredentialListMapping() {
}

@test:Config {}
isolated function  testFetchSipAuthCallsCredentialListMapping() {
}

@test:Config {}
isolated function  testDeleteSipAuthCallsCredentialListMapping() {
}

@test:Config {}
isolated function  testListSipAuthCallsIpAccessControlListMapping() {
}

@test:Config {}
isolated function  testCreateSipAuthCallsIpAccessControlListMapping() {
}

@test:Config {}
isolated function  testFetchSipAuthCallsIpAccessControlListMapping() {
}

@test:Config {}
isolated function  testDeleteSipAuthCallsIpAccessControlListMapping() {
}

@test:Config {}
isolated function  testListSipAuthRegistrationsCredentialListMapping() {
}

@test:Config {}
isolated function  testCreateSipAuthRegistrationsCredentialListMapping() {
}

@test:Config {}
isolated function  testFetchSipAuthRegistrationsCredentialListMapping() {
}

@test:Config {}
isolated function  testDeleteSipAuthRegistrationsCredentialListMapping() {
}

@test:Config {}
isolated function  testListSipCredential() {
}

@test:Config {}
isolated function  testCreateSipCredential() {
}

@test:Config {}
isolated function  testFetchSipCredential() {
}

@test:Config {}
isolated function  testUpdateSipCredential() {
}

@test:Config {}
isolated function  testDeleteSipCredential() {
}

@test:Config {}
isolated function  testListSipCredentialList() {
}

@test:Config {}
isolated function  testCreateSipCredentialList() {
}

@test:Config {}
isolated function  testFetchSipCredentialList() {
}

@test:Config {}
isolated function  testUpdateSipCredentialList() {
}

@test:Config {}
isolated function  testDeleteSipCredentialList() {
}

@test:Config {}
isolated function  testListSipCredentialListMapping() {
}

@test:Config {}
isolated function  testCreateSipCredentialListMapping() {
}

@test:Config {}
isolated function  testFetchSipCredentialListMapping() {
}

@test:Config {}
isolated function  testDeleteSipCredentialListMapping() {
}

@test:Config {}
isolated function  testListSipDomain() {
}

@test:Config {}
isolated function  testCreateSipDomain() {
}

@test:Config {}
isolated function  testFetchSipDomain() {
}

@test:Config {}
isolated function  testUpdateSipDomain() {
}

@test:Config {}
isolated function  testDeleteSipDomain() {
}

@test:Config {}
isolated function  testListSipIpAccessControlList() {
}

@test:Config {}
isolated function  testCreateSipIpAccessControlList() {
}

@test:Config {}
isolated function  testFetchSipIpAccessControlList() {
}

@test:Config {}
isolated function  testUpdateSipIpAccessControlList() {
}

@test:Config {}
isolated function  testDeleteSipIpAccessControlList() {
}

@test:Config {}
isolated function  testFetchSipIpAccessControlListMapping() {
}

@test:Config {}
isolated function  testDeleteSipIpAccessControlListMapping() {
}

@test:Config {}
isolated function  testListSipIpAccessControlListMapping() {
}

@test:Config {}
isolated function  testCreateSipIpAccessControlListMapping() {
}

@test:Config {}
isolated function  testListSipIpAddress() {
}

@test:Config {}
isolated function  testCreateSipIpAddress() {
}

@test:Config {}
isolated function  testFetchSipIpAddress() {
}

@test:Config {}
isolated function  testUpdateSipIpAddress() {
}

@test:Config {}
isolated function  testDeleteSipIpAddress() {
}

@test:Config {}
isolated function  testCreateSiprec() {
}

@test:Config {}
isolated function  testUpdateSiprec() {
}

@test:Config {}
isolated function  testCreateStream() {
}

@test:Config {}
isolated function  testUpdateStream() {
}

@test:Config {}
isolated function  testCreateToken() {
}

@test:Config {}
isolated function  testFetchTranscription() {
}

@test:Config {}
isolated function  testDeleteTranscription() {
}

@test:Config {}
isolated function  testListTranscription() {
}

@test:Config {}
isolated function  testListUsageRecord() {
}

@test:Config {}
isolated function  testListUsageRecordAllTime() {
}

@test:Config {}
isolated function  testListUsageRecordDaily() {
}

@test:Config {}
isolated function  testListUsageRecordLastMonth() {
}

@test:Config {}
isolated function  testListUsageRecordMonthly() {
}

@test:Config {}
isolated function  testListUsageRecordThisMonth() {
}

@test:Config {}
isolated function  testListUsageRecordToday() {
}

@test:Config {}
isolated function  testListUsageRecordYearly() {
}

@test:Config {}
isolated function  testListUsageRecordYesterday() {
}

@test:Config {}
isolated function  testFetchUsageTrigger() {
}

@test:Config {}
isolated function  testUpdateUsageTrigger() {
}

@test:Config {}
isolated function  testDeleteUsageTrigger() {
}

@test:Config {}
isolated function  testListUsageTrigger() {
}

@test:Config {}
isolated function  testCreateUsageTrigger() {
}

@test:Config {}
isolated function  testCreateUserDefinedMessage() {
}

@test:Config {}
isolated function  testCreateUserDefinedMessageSubscription() {
}

@test:Config {}
isolated function  testDeleteUserDefinedMessageSubscription() {
}
